#!/usr/bin/env bash

# Vaultwarden Setup Script (Podman + Tailscale edition)
#
# Sets up a Vaultwarden instance (self-hosted Bitwarden-compatible password
# manager) running in a Podman container, with TLS provided directly by
# Tailscale. No nginx or Let's Encrypt required — the droplet must already
# be joined to a Tailscale network with MagicDNS and HTTPS certificates
# enabled in the Tailscale admin console.
#
# What this script does:
#   1. Installs Podman and dependencies
#   2. Creates a persistent data directory at /srv/vaultwarden
#   3. Fetches a TLS certificate for the Tailscale hostname
#   4. Installs a daily cert-refresh cron job
#   5. Writes an env config file at /etc/vaultwarden/vaultwarden.conf
#   6. Writes a Podman Quadlet (.container) unit for the vaultwarden user
#   7. Pulls the Vaultwarden image
#   8. Activates the Quadlet unit via systemctl --user (a transient
#      vaultwarden.service is generated by the quadlet generator)
#
# Prerequisites:
#   - Tailscale is installed, running, and the machine is joined to your tailnet
#   - MagicDNS is enabled in the Tailscale admin console (DNS → Enable MagicDNS)
#   - HTTPS certificates are enabled in the Tailscale admin console (DNS → Enable HTTPS)
#   - UFW (or equivalent) is already configured
#   - A 'vaultwarden' rootless-Podman service account already exists. Create it by
#     running, from this repo:  sudo ./server/setup_rootless_podman.sh vaultwarden
#
# Usage:
#   sudo ./setup_vaultwarden.sh <tailscale-hostname> [options]
#
#   <tailscale-hostname> is the full MagicDNS name of this machine, e.g.:
#     my-droplet.tail1234.ts.net
#
# Options:
#   --port        Port to bind Vaultwarden on the Tailscale interface (default: 443)
#   --admin-token Token for the /admin interface (default: randomly generated)
#
# Examples:
#   sudo ./setup_vaultwarden.sh my-droplet.tail1234.ts.net
#   sudo ./setup_vaultwarden.sh my-droplet.tail1234.ts.net --port 8443
#
# After setup:
#   1. Visit https://<tailscale-hostname> and create your account
#   2. Visit https://<tailscale-hostname>/admin (using your admin token) to configure
#   3. Once your account is created, disable signups and the admin interface:
#        sudo ./setup_vaultwarden.sh harden
#      or edit /etc/vaultwarden/vaultwarden.conf manually and restart:
#        sudo -u vaultwarden XDG_RUNTIME_DIR=/run/user/$(id -u vaultwarden) \
#            systemctl --user restart vaultwarden

set -euo pipefail

# Source shared helpers (info/success/warn/error/section, require_root, ...).
# Two valid locations: the in-repo path (when invoked from a clone) and the
# installed path (when invoked from /usr/local/sbin/, e.g. by the cert-refresh
# cron job set up by this script's `setup` command).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
for _common_candidate in \
    "$SCRIPT_DIR/../lib/common.sh" \
    "/usr/local/lib/selfhosted-scripts/common.sh"; do
    if [[ -f "$_common_candidate" ]]; then
        # shellcheck source=../lib/common.sh
        . "$_common_candidate"
        break
    fi
done
unset _common_candidate

# Back-compat aliases: this script's body still uses print_* names.
# print_error is intentionally non-exiting (callers always follow it with an
# explicit `exit 1`); don't alias to error() which would exit.
print_info()    { info "$@"; }
print_success() { success "$@"; }
print_warning() { warn "$@"; }
print_error()   { echo "${_C_RED}[ERROR]${_C_NC} $*" >&2; }
print_section() { section "$@"; }

# Preserve the colour-variable names used in the final summary block.
GREEN="$_C_GREEN"; YELLOW="$_C_YELLOW"; NC="$_C_NC"

# ── Constants ─────────────────────────────────────────────────────────────────
# Pin to a specific version for reproducible deploys. To update, change this
# value and re-run the setup, or hand-edit the installed quadlet at
# /home/vaultwarden/.config/containers/systemd/vaultwarden.container and run
# `systemctl daemon-reload && systemctl --user restart vaultwarden` as the
# vaultwarden user.
# v1.35.4 ships Vaultwarden 1.35.4; WebSockets are on the main port (v1.29+).
VW_IMAGE="docker.io/vaultwarden/server:1.35.4"

# Dedicated unprivileged system user — Podman runs rootless under this account
# so a container escape cannot yield root on the host.
VW_SYSTEM_USER="vaultwarden"

VW_DATA_DIR="/srv/vaultwarden"
VW_CERT_DIR="/srv/vaultwarden/certs"
VW_CONF_DIR="/etc/vaultwarden"
VW_ENV_FILE="$VW_CONF_DIR/vaultwarden.conf"

# Quadlet (.container) file — a systemd-podman generator reads it on
# `systemctl --user daemon-reload` and synthesises a transient
# vaultwarden.service unit. See podman-systemd.unit(5). Quadlet ships with
# Podman 4.4+; Ubuntu 24.04's 4.9.3 supports it natively.
VW_QUADLET_DIR="/home/$VW_SYSTEM_USER/.config/containers/systemd"
VW_QUADLET_FILE="$VW_QUADLET_DIR/vaultwarden.container"

# Where this script and its shared helpers are installed during `setup`, so the
# cert-refresh cron job and post-setup invocations (`harden`, `cert-refresh`)
# work even if the original clone is deleted.
INSTALLED_SCRIPT="/usr/local/sbin/setup_vaultwarden.sh"
INSTALLED_COMMON="/usr/local/lib/selfhosted-scripts/common.sh"

# ── Root check ────────────────────────────────────────────────────────────────
require_root

# ── Tailscale check ───────────────────────────────────────────────────────────
# Verify the dedicated rootless-Podman service account this script expects.
# The user must already exist (created by setup_rootless_podman.sh) — we don't
# create it on the fly here, because doing so would skip all the rootless-
# Podman setup (subuid/subgid ranges, cgroup delegation, AppArmor patches,
# linger, port-binding sysctl) that script handles.
check_system_user() {
    if ! id "$VW_SYSTEM_USER" &>/dev/null; then
        print_error "System user '$VW_SYSTEM_USER' does not exist."
        print_error ""
        print_error "This script runs Vaultwarden as a dedicated rootless-Podman"
        print_error "service account that must be created beforehand. From the"
        print_error "root of this repo, run:"
        print_error ""
        print_error "    sudo ./server/setup_rootless_podman.sh $VW_SYSTEM_USER"
        print_error ""
        print_error "Then re-run this script."
        exit 1
    fi

    # Confirm linger is enabled — without it, the user's systemd session
    # (and therefore any container) is torn down when no login is active.
    if ! loginctl show-user "$VW_SYSTEM_USER" 2>/dev/null | grep -q "Linger=yes"; then
        print_error "User '$VW_SYSTEM_USER' exists but linger is not enabled."
        print_error "Re-run: sudo ./server/setup_rootless_podman.sh $VW_SYSTEM_USER"
        exit 1
    fi
}

# Run `systemctl --user <args>` as the vaultwarden user, against the user's
# systemd instance. This is the canonical pattern for managing rootless
# Podman Quadlet units from a root invocation (cron, this script, ...).
# XDG_RUNTIME_DIR must point at the tmpfs created for the user by
# systemd-logind when linger is active.
vw_systemctl() {
    local vw_uid
    vw_uid=$(id -u "$VW_SYSTEM_USER")
    sudo -u "$VW_SYSTEM_USER" \
        XDG_RUNTIME_DIR="/run/user/${vw_uid}" \
        systemctl --user "$@"
}

check_tailscale() {
    if ! command -v tailscale &>/dev/null; then
        print_error "Tailscale is not installed. Install and join your tailnet first."
        exit 1
    fi

    local ts_status
    ts_status=$(tailscale status --json 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('BackendState',''))" 2>/dev/null || echo "")
    if [[ "$ts_status" != "Running" ]]; then
        print_error "Tailscale is not running or not authenticated (state: ${ts_status:-unknown})"
        print_error "Run: tailscale up"
        exit 1
    fi
}

# ══════════════════════════════════════════════════════════════════════════════
# CERT REFRESH — fetch/renew Tailscale TLS cert and copy into the data dir
# ══════════════════════════════════════════════════════════════════════════════
cmd_cert_refresh() {
    local hostname="${1:-}"

    [[ -n "$hostname" ]] || error "hostname is required for cert-refresh"

    print_info "Fetching Tailscale TLS certificate for $hostname..."

    # Snapshot the fingerprint of the cert already in place (if any) so we can
    # detect whether tailscale cert actually issued a new one.
    local old_fingerprint=""
    if [[ -f "$VW_CERT_DIR/fullchain.pem" ]]; then
        old_fingerprint=$(openssl x509 -noout -fingerprint -sha256 \
            -in "$VW_CERT_DIR/fullchain.pem" 2>/dev/null || true)
    fi

    # Ensure the cert dir exists and has correct ownership/permissions whether
    # this is called from setup or standalone (e.g. cert-refresh subcommand).
    mkdir -p "$VW_CERT_DIR"
    chown root:"$VW_SYSTEM_USER" "$VW_CERT_DIR"
    chmod 750 "$VW_CERT_DIR"

    tailscale cert --cert-file "/var/lib/tailscale/certs/${hostname}.crt" \
                   --key-file  "/var/lib/tailscale/certs/${hostname}.key" \
                   "$hostname"

    cp "/var/lib/tailscale/certs/${hostname}.crt" "$VW_CERT_DIR/fullchain.pem"
    cp "/var/lib/tailscale/certs/${hostname}.key" "$VW_CERT_DIR/privkey.pem"

    # The key must be readable by the vaultwarden user (which runs the rootless
    # container) but not world-readable. The cert is public so 644 is fine.
    chown root:"$VW_SYSTEM_USER" "$VW_CERT_DIR/privkey.pem" "$VW_CERT_DIR/fullchain.pem"
    chmod 640 "$VW_CERT_DIR/privkey.pem"
    chmod 644 "$VW_CERT_DIR/fullchain.pem"

    print_success "Certificate copied to $VW_CERT_DIR"

    # Only restart if the cert actually changed — avoids a needless service
    # interruption on days when tailscale cert returns the cached cert unchanged.
    local new_fingerprint
    new_fingerprint=$(openssl x509 -noout -fingerprint -sha256 \
        -in "$VW_CERT_DIR/fullchain.pem" 2>/dev/null || true)

    if [[ "$old_fingerprint" = "$new_fingerprint" && -n "$new_fingerprint" ]]; then
        print_info "Certificate unchanged — skipping Vaultwarden restart"
    elif vw_systemctl is-active --quiet vaultwarden 2>/dev/null; then
        vw_systemctl restart vaultwarden
        print_success "Vaultwarden restarted to pick up new certificate"
    fi
}

# ══════════════════════════════════════════════════════════════════════════════
# HARDEN — disable signups and admin interface post-setup
# ══════════════════════════════════════════════════════════════════════════════
cmd_harden() {
    print_section "Hardening Vaultwarden"

    if [[ ! -f "$VW_ENV_FILE" ]]; then
        print_error "Vaultwarden config not found at $VW_ENV_FILE"
        print_error "Has Vaultwarden been set up yet?"
        exit 1
    fi

    # Disable signups
    if grep -q '^SIGNUPS_ALLOWED=false' "$VW_ENV_FILE"; then
        print_info "SIGNUPS_ALLOWED already false — skipping"
    else
        sed -i 's/^SIGNUPS_ALLOWED=.*/SIGNUPS_ALLOWED=false/' "$VW_ENV_FILE"
        print_success "Signups disabled"
    fi

    # Disable admin interface
    if grep -q '^#ADMIN_TOKEN=' "$VW_ENV_FILE"; then
        print_info "Admin interface already disabled — skipping"
    elif grep -q '^ADMIN_TOKEN=' "$VW_ENV_FILE"; then
        sed -i 's/^ADMIN_TOKEN=/#ADMIN_TOKEN=/' "$VW_ENV_FILE"
        print_success "Admin interface disabled"
    else
        print_warning "ADMIN_TOKEN line not found in $VW_ENV_FILE — check manually"
    fi

    vw_systemctl restart vaultwarden
    print_success "Vaultwarden restarted with hardened config"
    print_info "To re-enable the admin interface, edit $VW_ENV_FILE,"
    print_info "uncomment ADMIN_TOKEN, and run:"
    print_info "  sudo -u $VW_SYSTEM_USER XDG_RUNTIME_DIR=/run/user/\$(id -u $VW_SYSTEM_USER) systemctl --user restart vaultwarden"
    echo ""
}

# ══════════════════════════════════════════════════════════════════════════════
# SETUP
# ══════════════════════════════════════════════════════════════════════════════
cmd_setup() {
    # ── Parse arguments ───────────────────────────────────────────────────────
    local hostname="${1:-}"; shift
    local port=443 admin_token=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --port)         port="$2";         shift 2 ;;
            --admin-token)  admin_token="$2";  shift 2 ;;
            --help|-h)      cmd_help; exit 0 ;;
            *) print_error "Unknown option: $1"; exit 1 ;;
        esac
    done

    [[ -z "$hostname" ]] && { print_error "Tailscale hostname is required"; exit 1; }

    if ! [[ "$port" =~ ^[0-9]+$ ]] || (( port < 1 || port > 65535 )); then
        print_error "Invalid port '$port' — must be an integer between 1 and 65535"
        exit 1
    fi

    # ── Preflight checks ──────────────────────────────────────────────────────
    check_system_user
    check_tailscale

    # Resolve the Tailscale IP for this machine — used to bind Rocket to the
    # Tailscale interface only, so Vaultwarden is not reachable on the public IP
    local ts_ip
    ts_ip=$(tailscale ip -4 2>/dev/null || true)
    if [[ -z "$ts_ip" ]]; then
        print_error "Could not determine Tailscale IPv4 address. Is the machine on the tailnet?"
        exit 1
    fi
    print_info "Tailscale IPv4: $ts_ip"

    # Validate that the supplied hostname matches this machine's actual Tailscale
    # MagicDNS name. A mismatch means the cert will be for the wrong host.
    local actual_hostname
    actual_hostname=$(tailscale status --json 2>/dev/null \
        | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['Self']['DNSName'].rstrip('.'))" \
        2>/dev/null || echo "")
    if [[ -z "$actual_hostname" ]]; then
        print_warning "Could not verify Tailscale hostname (MagicDNS may not be enabled)."
        print_warning "Continuing with supplied hostname: $hostname"
    elif [[ "$hostname" != "$actual_hostname" ]]; then
        print_error "Supplied hostname '$hostname' does not match this machine's Tailscale hostname '$actual_hostname'."
        print_error "The TLS certificate would be for the wrong host. Did you mean:"
        print_error "  sudo $0 $actual_hostname"
        exit 1
    else
        print_info "Hostname verified: $hostname"
    fi

    # Check for existing installation before doing anything destructive
    if [[ -f "$VW_ENV_FILE" || -f "$VW_QUADLET_FILE" ]]; then
        print_error "Vaultwarden appears to already be installed."
        print_error "To remove it, stop and disable the service, then remove $VW_CONF_DIR and $VW_DATA_DIR."
        exit 1
    fi

    # Generate the raw admin token now (before any installs) so we can fail
    # fast on bad input. The actual Argon2 hashing happens after Step 1
    # installs the argon2 package.
    if [[ -z "$admin_token" ]]; then
        admin_token=$(openssl rand -hex 32)
    fi

    print_section "Setting up Vaultwarden on $hostname (port $port)"

    # ── Step 1: Install dependencies ──────────────────────────────────────────
    print_info "Step 1: Installing argon2..."
    apt-get update -qq
    # podman-compose is no longer needed — we use Quadlet (.container files)
    # which generates a systemd unit directly, without docker-compose.
    apt-get install -y argon2
    print_success "Dependencies installed"

    # Hash the admin token now that argon2 is available.
    # Vaultwarden expects an Argon2id hash in ADMIN_TOKEN — storing plaintext
    # works but triggers a startup warning and exposes the token in the config.
    # The raw token goes into a root-only reveal file; never to the terminal.
    local salt
    salt=$(openssl rand -base64 16)
    local admin_token_hash
    admin_token_hash=$(echo -n "$admin_token" | argon2 "$salt" -id -t 3 -m 17 -p 4 -l 32 -e)

    # Write the raw token to a one-time reveal file, never to the terminal.
    local token_reveal_file="/root/vaultwarden-admin-token.txt"
    if [[ -f "$token_reveal_file" ]]; then
        print_error "$token_reveal_file already exists from a previous (partial?) run."
        print_error "Remove it first: sudo rm $token_reveal_file"
        print_error "If you still have the token it contained, that's fine — it won't be reused."
        exit 1
    fi
    cat > "$token_reveal_file" << EOF
Vaultwarden admin token — delete this file after noting the token down.
Generated: $(date)

Raw token (paste this into the /admin login page):
$admin_token

The Argon2 hash of this token is stored in $VW_ENV_FILE.
EOF
    chmod 600 "$token_reveal_file"
    print_info "Admin token written to $token_reveal_file (root-only)"
    print_warning "Read it with: sudo cat $token_reveal_file"
    print_warning "Delete it after noting the token: sudo rm $token_reveal_file"

    # ── Step 2: Create system user and directories ────────────────────────────
    print_info "Step 2: Creating directories..."

    mkdir -p "$VW_DATA_DIR"
    mkdir -p "$VW_CERT_DIR"
    mkdir -p "$VW_CONF_DIR"
    # Data dir is owned by the system user.
    chown -R "$VW_SYSTEM_USER:$VW_SYSTEM_USER" "$VW_DATA_DIR"
    # Config dir stays root-owned (it holds the admin token hash) but the
    # vaultwarden user needs execute permission to enter it so it can read
    # the group-readable env file referenced by the Quadlet's EnvironmentFile=.
    chown root:"$VW_SYSTEM_USER" "$VW_CONF_DIR"
    chmod 750 "$VW_CONF_DIR"
    print_success "Directories created"

    # ── Step 3: Fetch TLS certificate ─────────────────────────────────────────
    print_section "Step 3: Fetching Tailscale TLS certificate"
    print_info "This requires HTTPS certificates to be enabled in your Tailscale admin console"
    print_info "(DNS → Enable HTTPS)"
    cmd_cert_refresh "$hostname"

    # ── Step 4: Install this script + cert-refresh cron job ──────────────────
    print_info "Step 4: Installing script and certificate refresh cron job..."

    # Install the script and its sourced helper to fixed paths so that the
    # cert-refresh cron job and the post-setup `harden` / `cert-refresh`
    # subcommands work even if the original clone directory is deleted.
    #
    # Previously this step generated a separate /usr/local/bin/vaultwarden-cert-refresh
    # wrapper that inlined the cert-refresh logic. That duplicated cmd_cert_refresh()
    # and the two implementations could drift. Now cron just calls back into
    # this script's `cert-refresh` subcommand — single source of truth.
    install -m 755 "${BASH_SOURCE[0]}" "$INSTALLED_SCRIPT"
    install -d -m 755 "$(dirname "$INSTALLED_COMMON")"
    install -m 644 "$SCRIPT_DIR/../lib/common.sh" "$INSTALLED_COMMON"
    print_success "Script installed at $INSTALLED_SCRIPT"

    # Run daily at 04:00 — Tailscale certs are valid for ~90 days so this is
    # ample headroom. `tailscale cert` is a no-op if the cert is still fresh,
    # and cmd_cert_refresh() skips the Vaultwarden restart if the cert
    # fingerprint is unchanged.
    cat > /etc/cron.d/vaultwarden-cert-refresh << CRON_EOF
# Vaultwarden Tailscale cert refresh — managed by setup_vaultwarden.sh
0 4 * * * root $INSTALLED_SCRIPT cert-refresh $hostname >> /var/log/vaultwarden-cert-refresh.log 2>&1
CRON_EOF
    print_success "Cron job installed: daily at 04:00 (calls $INSTALLED_SCRIPT cert-refresh)"

    # ── Step 5: Write env config ──────────────────────────────────────────────
    print_info "Step 5: Writing Vaultwarden config to $VW_ENV_FILE..."

    cat > "$VW_ENV_FILE" << EOF
# Vaultwarden environment configuration
# Managed by setup_vaultwarden.sh
#
# After creating your account, run: sudo ./setup_vaultwarden.sh harden
# This will set SIGNUPS_ALLOWED=false and disable the admin interface.

# Bind Rocket to all interfaces inside the container.
ROCKET_ADDRESS=0.0.0.0

# Port Vaultwarden's web server (Rocket) listens on.
ROCKET_PORT=$port

# TLS certificate and key — provided by Tailscale, refreshed daily by cron.
# These paths are inside the container (mounted from $VW_CERT_DIR on the host).
ROCKET_TLS={certs="/data/certs/fullchain.pem",key="/data/certs/privkey.pem"}

# Allow new user registrations. Set to false after creating your account
# by running: sudo ./setup_vaultwarden.sh harden
SIGNUPS_ALLOWED=true

# Require email verification on signup (requires SMTP config below)
SIGNUPS_VERIFY=false

# Prevent users from creating organisations (and thus inviting others).
# Set to a comma-separated list of email addresses to whitelist specific users,
# or leave empty ("") to allow all users to create orgs.
ORG_CREATION_USERS=none

# Admin interface token — treat this like a password.
# Stored as an Argon2id hash; paste the RAW token (from /root/vaultwarden-admin-token.txt)
# into the browser, NOT the hash. Comment out to disable the /admin interface entirely.
ADMIN_TOKEN=ADMIN_TOKEN_PLACEHOLDER

# Don't show password hints on the login page
SHOW_PASSWORD_HINT=false

# --- Optional: SMTP for email notifications and signup verification ---
# Uncomment and fill in to enable email support.
#SMTP_HOST=smtp.example.com
#SMTP_PORT=587
#SMTP_SECURITY=starttls
#SMTP_USERNAME=you@example.com
#SMTP_PASSWORD=yourpassword
#SMTP_FROM=vaultwarden@example.com
EOF

    # Protect the config — it contains the admin token hash.
    # Group-readable so the vaultwarden user (which runs podman) can read it;
    # root-owned so only root can modify it.
    chown root:"$VW_SYSTEM_USER" "$VW_ENV_FILE"
    chmod 640 "$VW_ENV_FILE"

    # Substitute the placeholder with the Argon2 hash. Use | as the sed
    # delimiter since the hash contains / characters. The hash may also
    # contain & which sed treats specially in the replacement — escape it.
    local safe_hash
    safe_hash=$(echo "$admin_token_hash" | sed 's/[&/\]/\\&/g')
    sed -i "s|ADMIN_TOKEN_PLACEHOLDER|${safe_hash}|" "$VW_ENV_FILE"

    print_success "Config written (permissions: root-only read)"

    # ── Step 6: Write Quadlet (.container) unit ───────────────────────────────
    # See podman-systemd.unit(5). systemd's quadlet generator reads .container
    # files on `systemctl --user daemon-reload` and synthesises a matching
    # vaultwarden.service unit at runtime.
    print_info "Step 6: Writing Quadlet unit to $VW_QUADLET_FILE..."

    sudo -u "$VW_SYSTEM_USER" mkdir -p "$VW_QUADLET_DIR"

    sudo -u "$VW_SYSTEM_USER" tee "$VW_QUADLET_FILE" > /dev/null << EOF
# Vaultwarden — managed by setup_vaultwarden.sh
# Quadlet generates vaultwarden.service from this file.
#
# Manage as the vaultwarden user (linger keeps the user session alive):
#   sudo -u $VW_SYSTEM_USER XDG_RUNTIME_DIR=/run/user/\$(id -u $VW_SYSTEM_USER) \\
#       systemctl --user {start,stop,restart,status} vaultwarden
#   journalctl --user-unit vaultwarden -f
#
# Update:  change Image= here (or VW_IMAGE in setup_vaultwarden.sh), then:
#   sudo -u $VW_SYSTEM_USER podman pull <new image>
#   sudo -u $VW_SYSTEM_USER systemctl --user daemon-reload
#   sudo -u $VW_SYSTEM_USER systemctl --user restart vaultwarden
#   sudo -u $VW_SYSTEM_USER podman image prune -f

[Unit]
Description=Vaultwarden password manager (Podman Quadlet + Tailscale)
Documentation=https://github.com/dani-garcia/vaultwarden

[Container]
Image=$VW_IMAGE
ContainerName=vaultwarden
EnvironmentFile=$VW_ENV_FILE
# Persistent data (SQLite DB, attachments, etc.) and TLS certs.
# :Z relabels for SELinux; harmless on Ubuntu (AppArmor) but kept for portability.
Volume=$VW_DATA_DIR:/data:Z
# Bind only to the Tailscale interface — not reachable on the public IP.
PublishPort=$ts_ip:$port:$port
# Defense-in-depth resource limits in case of container escape or runaway process.
PodmanArgs=--memory=512m --pids-limit=512

[Service]
# Restart on failure, but not on clean exits (e.g. manual stop).
Restart=on-failure
RestartSec=10

[Install]
# default.target is the rootless-user equivalent of multi-user.target.
WantedBy=default.target
EOF

    chmod 644 "$VW_QUADLET_FILE"
    print_success "Quadlet unit written"

    # ── Step 7: Pull image ────────────────────────────────────────────────────
    print_info "Step 7: Pulling Vaultwarden image ($VW_IMAGE)..."
    sudo -u "$VW_SYSTEM_USER" XDG_RUNTIME_DIR="/run/user/$(id -u "$VW_SYSTEM_USER")" \
        podman pull "$VW_IMAGE"
    print_success "Image pulled"

    # ── Step 8: Activate Quadlet unit ─────────────────────────────────────────
    # daemon-reload triggers the quadlet generator to read VW_QUADLET_FILE and
    # produce a transient vaultwarden.service unit in the user session.
    print_info "Step 8: Activating Quadlet unit..."

    vw_systemctl daemon-reload
    # Quadlet-generated units cannot be `enable`d (they're transient — they
    # are regenerated on every daemon-reload), but `WantedBy=default.target`
    # in the .container file makes them start automatically with the user
    # session, which linger keeps alive across reboots.
    vw_systemctl start vaultwarden.service
    print_success "Quadlet unit activated and started"

    # ── Step 9: Health check ──────────────────────────────────────────────────
    print_info "Waiting for Vaultwarden to be ready..."
    local healthy=false
    local retries=12  # 12 × 5s = 60s timeout
    for (( i=1; i<=retries; i++ )); do
        # Use --resolve to map the Tailscale hostname to its IP so curl can
        # verify the TLS certificate's SAN properly — avoids --insecure.
        if curl -sf --resolve "${hostname}:${port}:${ts_ip}" \
                "https://${hostname}:${port}/alive" &>/dev/null; then
            healthy=true
            print_success "Vaultwarden is responding on $hostname:$port"
            break
        fi
        print_info "  Not ready yet (attempt $i/$retries) — waiting 5s..."
        sleep 5
    done

    if [[ "$healthy" = false ]]; then
        print_warning "Vaultwarden didn't respond after 60s"
        print_warning "Check logs with: sudo -u $VW_SYSTEM_USER journalctl --user-unit vaultwarden -n 50"
    fi

    # ── Done ──────────────────────────────────────────────────────────────────
    print_section "Vaultwarden setup complete"
    echo ""
    echo -e "  ${GREEN}https://$hostname${NC}"
    echo ""
    print_warning "Next steps:"
    echo -e "  ${YELLOW}1. Visit https://$hostname and create your account${NC}"
    echo -e "  ${YELLOW}2. Visit https://$hostname/admin to configure Vaultwarden${NC}"
    echo -e "     ${YELLOW}Admin token: sudo cat $token_reveal_file${NC}"
    echo -e "     ${YELLOW}Delete after use: sudo rm $token_reveal_file${NC}"
    echo -e "  ${YELLOW}3. Once your account is set up, lock down the instance:${NC}"
    echo -e "     ${YELLOW}sudo $0 harden${NC}"
    echo ""
    print_info "Useful commands:"
    print_info "  Logs:          sudo -u $VW_SYSTEM_USER journalctl --user-unit vaultwarden -f"
    print_info "  Restart:       sudo -u $VW_SYSTEM_USER XDG_RUNTIME_DIR=/run/user/\$(id -u $VW_SYSTEM_USER) systemctl --user restart vaultwarden"
    print_info "  Status:        sudo -u $VW_SYSTEM_USER XDG_RUNTIME_DIR=/run/user/\$(id -u $VW_SYSTEM_USER) systemctl --user status vaultwarden"
    print_info "  Config:        $VW_ENV_FILE"
    print_info "  Data:          $VW_DATA_DIR"
    print_info "  Cert refresh:  $INSTALLED_SCRIPT cert-refresh $hostname  (cron: /etc/cron.d/vaultwarden-cert-refresh)"
    echo ""
    print_info "To update Vaultwarden in future:"
    print_info "  sudo -u $VW_SYSTEM_USER podman pull <new image>"
    print_info "  sudo -u $VW_SYSTEM_USER XDG_RUNTIME_DIR=/run/user/\$(id -u $VW_SYSTEM_USER) \\"
    print_info "      systemctl --user daemon-reload && systemctl --user restart vaultwarden"
    print_info "  sudo -u $VW_SYSTEM_USER podman image prune -f   # clean up the old image"
    echo ""
}

# ══════════════════════════════════════════════════════════════════════════════
# HELP
# ══════════════════════════════════════════════════════════════════════════════
cmd_help() {
    grep '^#' "$0" | grep -v '^#!/' | sed 's/^# \?//'
}

# ══════════════════════════════════════════════════════════════════════════════
# ENTRYPOINT
# ══════════════════════════════════════════════════════════════════════════════
case "${1:-}" in
    harden)       cmd_harden ;;
    cert-refresh) cmd_cert_refresh "${2:-}" ;;
    --help|-h)    cmd_help ;;
    "")
        print_error "Usage: $0 <tailscale-hostname> [options]"
        print_error "       $0 harden"
        print_error "       $0 cert-refresh <tailscale-hostname>"
        exit 1
        ;;
    *)
        cmd_setup "$@"
        ;;
esac
